### ISSUE TITLE
[Bug]: changelog missing for 25.0.5

### ISSUE THREAD

**Issue by iniOr** [nextcloud/nextcloud-theme#34]
### Bug description

https://nextcloud.com/changelog/#25-0-5 is not existing in the https://nextcloud.com/changelog/ page.

When the update is shown in the admin interface the changelog should be accessible at the exact same time, this issue was already present for the previous releases.

When the update is shown in the admin interface the changelog link should be working as expected.

### Steps to reproduce

1.Get notified of a new update
2.try to consult the changelog
3.the changelog is always missing (it is still the case after one week currently for version 25.0.5)

### Expected behavior

The changelog shoud be available at the exact same time of the update notification.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

**Comment by szaimen** [comment]
cc @peterwebdesign

**Comment by peterwebdesign** [comment]
this is now fixed
