### ISSUE TITLE
incorrect URL - ./pushnotifications -> "Nextcloud Fair Use Policy and NGO program"

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#39]
The URL `https://nextcloud.com/pushnotifications/` leads to a page titled "Nextcloud Fair Use Policy and NGO program"

This URL feels at best mismatched with the content, as there is no mention of push notifications anywhere on the page.

URL: https://nextcloud.com/pushnotifications/

### Suggested solution:
* change the URL for the content to something more appropriate, i.e. `fair-use` or `ngo-program`, etc
* have ./pushnotifications point to a more appropriate blog/page/apps store entry?

**Comment by peterwebdesign** [comment]
set up a redirect to a renamed page https://nextcloud.com/fairusepolicy/
