### ISSUE TITLE
Conference - inorrect Motion.Lab graphic placement

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#40]
The MotionLab logo features a rather odd placement - imagining this is unintentional as it straddles two discrete sections - Nextcloud Include and Event Location.

location: https://nextcloud.com/conference-2023/

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/b6659203-cfcf-4e36-89d3-45a621014087)

**Comment by peterwebdesign** [comment]
this part of the design is intentional :)
