### ISSUE TITLE
./clients - banner image clashes with site menu

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#42]
https://nextcloud.com/clients/

The banner image on this page features LOTS of white, i.e. clouds. Unfortunately this visually clashes with the site's main navigation functions and menus (and page title, and subtitle, and..).

Suggesting a simple swap to something more design-appropriate.

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/723e11b1-1910-42a8-8ee9-5e5d56345cd9)

**Comment by peterwebdesign** [comment]
ah you're right, this was an old page that needed a redesign. But it is now gone, as we redirected it to the features page.
