### ISSUE TITLE
./enterprise - 

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#43]
The final button on this [Enterprise page](https://nextcloud.com/enterprise/) features a text and a link that feels out of place: `Get Nextcloud at home` w link location `https://nextcloud.com/athome/`

I believe this is intended to be `Get Nextcloud Enterprise` with an appropriate link.

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/310f3621-1e6e-4c0d-8acf-c8bd6d57b9a8)

**Comment by jospoortvliet** [comment]
Our idea was to have a link to the Nextcloud page for home users - but soon we'll deploy a new version of the page that doesn't have this problem anymore, anyhow. Thanks for pointing it out!
