### ISSUE TITLE
About - add new items to timeline

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#44]
The Timeline on https://nextcloud.com/about/ features events up to 2021. 
There is an opportunity to update this to include current events.

Ideas:
* introduction of Nextcloud's Ethical AI Rating system - a leading industry concept in Hub 4
* update number of installations

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/6f589783-0e06-4cd7-8ae0-36030e798d4a)

**Comment by jospoortvliet** [comment]
Done ;-)
