### ISSUE TITLE
security - outdated "Supported Product Versions"

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#47]
https://nextcloud.com/security/

Nextcloud server 26 & 27 are missing here.

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/7a6e6b03-e01c-4187-a39a-fb186cdc4daf)

From the [server repo release schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule):

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/16778ec7-9988-491b-8c1a-99bd4495e3cd)

**Comment by peterwebdesign** [comment]
this is now fixed, added 27, 26 and removed 24.
thanks for pointing this out Brent!
