### ISSUE TITLE
Assets - Hub 6 -> Hub 7 

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#51]
A list of items on the website that need updating from Hub 6 to Hub 7:
@peterwebdesign

**Comment by gerbrent** [comment]
[ ] See it in Action video
![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/291f5323-73bd-4aff-aa0d-6feb15700509)

**Comment by peterwebdesign** [comment]
this is now done
