### ISSUE TITLE
Changelog is always missing when update are published

### ISSUE THREAD

**Issue by iniOr** [nextcloud/nextcloud-theme#52]
Hi now the version 27.1.5 is not available from changelog page, why it is the same at every update ?
Upgrading software without a changelog ?

https://nextcloud.com/changelog/#27-1-5 -> broken link.

Exactly the same issue as reported previously : https://github.com/nextcloud/nextcloud-theme/issues/34

**Comment by peterwebdesign** [comment]
This is fixed now and the link should be working. 
Thanks for pointing that out!
