### ISSUE TITLE
blog - Hub 7 duplicate

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#54]
At https://nextcloud.com/blog/ there's a duplicate post for Hub 7 release blog:

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/ebbdc6ad-b9ee-4197-89a6-8119bd528c31)

**Comment by peterwebdesign** [comment]
I cannot replicate.. Is it after clicking on "Load more"? I tried it but everything looks good

**Comment by gerbrent** [comment]
hmm, fascinating!

Cannot reproduce now so... will close!
