### ISSUE TITLE
About us - page item overlaps in smaller viewport 

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#57]
https://nextcloud.com/about/

From 770-1000px viewport widths, two items overlap:

![image](https://github.com/nextcloud/nextcloud-theme/assets/7018928/08d2c2c8-e3d5-491f-8d7d-6b1263809c9d)

This may be true of other such items interacting on other pages aswell.

**Comment by peterwebdesign** [comment]
this is now fixed, thanks for pointing it out Brent
