### ISSUE TITLE
menu - resize while menu open breaks site

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/nextcloud-theme#58]
Summary: 

If you resize the browser window while the website menu is open, especially from small viewport to larger viewport - the website becomes quite broken.

![Peek 2024-01-25 14-41](https://github.com/nextcloud/nextcloud-theme/assets/7018928/ae6123f1-20d2-4cf2-8e66-8485cfb0eac7)

Steps to reproduce:

* navigate to https://nextcloud.com
* resize window to a small viewport, < 1000px wide
* open navigation menu
* resize window to larger viewport

result:
* screen fills with blue background colour
* top banner w featured artiles becomes blank
* page content vanishes
* language selector cut off
*

**Comment by peterwebdesign** [comment]
good catch, this should be fixed now
