### ISSUE TITLE
Request to remove Proton Mail and SimpleLogin addresses from your list of disposable emails

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [nextcloud/nextcloud-theme#61]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present [your list of disposable emails](https://github.com/nextcloud/nextcloud-theme/blob/063895ee8d0fd64d41a58f29a8ac308e20be843b/inc/disposable_email_blocklist_private.txt). To be more precise, proton.me, simplelogin.com, and slmail.me, are included.

At Proton, we take anti-abuse especially seriously and would like to work with you on having the abovementioned domains removed from your list. Can you elaborate why these domains are listed? Would it be possible to correct this?

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

**Comment by peterwebdesign** [comment]
Hello Nikola,
I'm sorry, but we cannot remove those domains from our list, as our website should restrict all form submissions exclusively to business emails.
