### ISSUE TITLE
Can't put hex code in user settings

### ISSUE THREAD

**Issue by NatoBoram** [nextcloud/nextcloud-theme#75]
User settings:

![image](https://github.com/nextcloud/nextcloud-theme/assets/10495562/5fd06848-61d4-4285-a678-cb472338fc2d)

Admin settings:

![image](https://github.com/nextcloud/nextcloud-theme/assets/10495562/7a0cb1e2-f598-47ed-becd-6509aa80f0b8)

**Comment by peterwebdesign** [comment]
Hi @NatoBoram - this repo is for the website only. To report Nextcloud related issues instead, you can open a GH issue here https://github.com/nextcloud/server/issues
